server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: deepseek-chat
  # application.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB